name: roin-video
version: '0.6'
summary: Remote control Roin video
description: Allows you to remotely watch video from the Roin through the control cabinet
base: core20
confinement: strict
grade: stable

plugs:
  read-config:
    interface: personal-files
    read:
      - $HOME/ROIN/config.txt

apps:
  daemon:
    daemon: simple
    restart-condition: always
    command-chain:
      - bin/run-daemon
      - bin/wayland-launch
    command: bin/run.sh
    plugs:
      -  opengl
      -  wayland
      -  network
      -  read-config

  roin-video:
    command-chain:
      - bin/wayland-launch
    command: bin/run.sh
    plugs:
      -  opengl
      -  wayland
      -  network
      -  read-config

  nano:
    command: bin/nano


layout:
  /usr/share/X11/locale:
    bind: $SNAP/usr/share/X11/locale
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/pulseaudio:
    bind: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/pulseaudio
     

environment:
  LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}:${SNAP}/usr/lib/:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/
  PATH: $SNAP/bin/:$SNAP/usr/bin/:${PATH}
  # Prep EGL
  __EGL_VENDOR_LIBRARY_DIRS: $SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d
  LIBGL_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
  LIBVA_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri

parts:      
  myprog:
    plugin: dump
    source: ./bin/${SNAPCRAFT_ARCH_TRIPLET}
    organize:
      Qml4RTSP: bin/Qml4RTSP
      
  run-scripts:
    plugin: dump
    source: ./bin/general
    organize:
      run.sh: bin/run.sh
            
  mesa:
    plugin: nil
    stage-packages:
      - libwayland-egl1-mesa
      - libgles2
      - libgles2-mesa
      - ubuntu-restricted-extras
      - libpulse0
      - nano
      #qt5     
      - qt5-default
      - qtdeclarative5-dev
      - qml-module-qtquick-window2
      - libqt5multimedia5-plugins
      - qml-module-qtmultimedia
      - qtwayland5

  get-run-rules:
    plugin: nil
    override-prime: |
      chmod +x $SNAPCRAFT_PRIME/bin/Qml4RTSP
      chmod +x $SNAPCRAFT_PRIME/bin/run.sh
    after:
      - myprog
      - run-scripts
      
  mir-kiosk-snap-launch:
    plugin: dump
    source: https://github.com/MirServer/mir-kiosk-snap-launch.git
    override-build:  $SNAPCRAFT_PART_BUILD/build-with-plugs.sh opengl wayland network
    stage-packages:
      - inotify-tools
