name: roin-video
version: '1.01'
summary: Remote control Roin video
description: Allows you to remotely watch video from the Roin through the control cabinet
base: core20
confinement: strict
grade: stable
architectures:
  - build-on: amd64
  - build-on: arm64

plugs:
  dot-config-roin:
    interface: personal-files
    read:
      - $HOME/.config/roin.txt
    write:
      - $HOME/.config/roin.txt
    

apps:
  daemon:
    daemon: simple
    restart-condition: always
    command-chain:
      - bin/run-daemon
      - bin/wayland-launch
    command: bin/run.sh
    plugs:
      -  opengl
      -  wayland
      -  network
      -  dot-config-roin

  roin-video:
    command-chain:
      - bin/wayland-launch
    command: bin/run.sh
    plugs:
      -  opengl
      -  wayland
      -  network
      -  dot-config-roin

  config:
    command: bin/nano /root/.config/roin.txt
    plugs:
      -  dot-config-roin


layout:
  /usr/share/X11/locale:
    bind: $SNAP/usr/share/X11/locale
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/pulseaudio:
    bind: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/pulseaudio
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/gstreamer-1.0:
    bind: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/gstreamer-1.0
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/gstreamer1.0:
    bind: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/gstreamer1.0
     

environment:
  LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}:${SNAP}/usr/lib/:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/
  PATH: $SNAP/bin/:$SNAP/usr/bin/:${PATH}
  # Prep EGL
  __EGL_VENDOR_LIBRARY_DIRS: $SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d
  LIBGL_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
  LIBVA_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri

parts:      
  myprog:
    plugin: dump
    source: ./bin/${SNAPCRAFT_ARCH_TRIPLET}
    organize:
      Qml4RTSP: bin/Qml4RTSP
      
  run-scripts:
    plugin: dump
    source: ./bin/general
    organize:
      run.sh: bin/run.sh
            
  mesa:
    plugin: nil
    stage-packages:
      - libwayland-egl1-mesa
      - libgles2
      - libgles2-mesa
      - libpulse0
      - freeglut3
      - nano
      #gsteamer
      - gstreamer1.0-rtsp
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-pulseaudio
      #qt5     
      - qt5-default
      - qtdeclarative5-dev
      - qml-module-qtquick-window2
      - libqt5multimedia5-plugins
      - qml-module-qtmultimedia
      - qtwayland5

  get-run-rules:
    plugin: nil
    override-prime: |
      chmod +x $SNAPCRAFT_PRIME/bin/Qml4RTSP
      chmod +x $SNAPCRAFT_PRIME/bin/run.sh
    after:
      - myprog
      - run-scripts
      
  mir-kiosk-snap-launch:
    plugin: dump
    source: https://github.com/MirServer/mir-kiosk-snap-launch.git
    override-build:  $SNAPCRAFT_PART_BUILD/build-with-plugs.sh opengl wayland network dot-config-roin
    stage-packages:
      - inotify-tools
